export const FETCH_PARTICIPATORY_BUDGET_ITEM_START = 'FETCH_PARTICIPATORY_BUDGET_ITEM_START';
export const FETCH_PARTICIPATORY_BUDGET_ITEM_SUCCESS = 'FETCH_PARTICIPATORY_BUDGET_ITEM_SUCCESS';
export const FETCH_PARTICIPATORY_BUDGET_ITEM_FAIL = 'FETCH_PARTICIPATORY_BUDGET_ITEM_FAIL';

export const FETCH_COUNCIL_MEMBER_START = 'FETCH_COUNCIL_MEMBER_START';
export const FETCH_COUNCIL_MEMBER_SUCCESS = 'FETCH_COUNCIL_MEMBER_SUCCESS';
export const FETCH_COUNCIL_MEMBER_FAIL = 'FETCH_COUNCIL_MEMBER_FAIL';

export const FETCH_DISTRICTS_START = 'FETCH_DISTRICTS_START';
export const FETCH_DISTRICTS_SUCCESS = 'FETCH_DISTRICTS_SUCCESS';
export const FETCH_DISTRICTS_FAIL = 'FETCH_DISTRICTS_FAIL';

export const BUDGET_FILTER = 'BUDGET_FILTER';
export const BUDGET_BY_YEAR = 'BUDGET_BY_YEAR';
export const BUDGET_BY_DISTRICT = 'BUDGET_BY_DISTRICT';
export const BUDGET_BY_CATEGORY = 'BUDGET_BY_CATEGORY';
export const RESET_SELECTED_ITEMS = 'RESET_SELECTED_ITEMS';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';

export const SET_MAP = 'SET_MAP';
export const UPDATE_MAP = 'UPDATE_MAP';
export const RESET_MAP = 'RESET_MAP';
export const ZOOM_MARKER = 'ZOOM_MARKER';
export const ZOOM_IN = 'ZOOM_IN';
export const ZOOM_OUT = 'ZOOM_OUT';
export const CENTER = 'CENTER';
export const SHOW_DISTRICTS = 'SHOW_DISTRICTS';